apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: wifi-logs-analysis-pr
  annotations:
    pipelinesascode.tekton.dev/on-event: "[pull_request]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
spec:
  pipelineRef:
    name: python-test
  params:
    - name: APP_NAME
      value: wifi-logs-analysis
    - name: SOURCE_URL
      value: https://github.com/vaibhav-r-pandey/wifi-logs-analysis.git
    - name: PYTHON_VERSION
      value: "3.10"
  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi